---
title: "Readiness to Change"
author: "Benjamin Carter"
date: "6/20/2020"
output:
  slidy_presentation:
    incremental: yes
  ioslides_presentation:
    incremental: yes
    widescreen: true
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
# paths V:\Depts\CtrTransRsch\Dept Private\CTR Staff\PROJECT - Readiness to change manuscript\DATA
data.dir.path <- file.path(
  "V:",
  "Depts", 
  "CtrTransRsch", 
  "Dept Private", 
  "CTR Staff", 
  "PROJECT - Readiness to change manuscript", 
  "DATA"
  )
```

```{r loadData, include=FALSE}
df <- readxl::read_xlsx(
  file.path(data.dir.path, "Nick_Rural16_OAT 6-11-20.xlsx")
  )

```


```{r selection}
df.processed <- df %>% 
  mutate(
    Gender = ifelse(
      Gender == 1,
      "Female",
      "Male"
      ),
    rtc_diet = ifelse(
      `1a_pre` == 1,
      "precontemplative",
      ifelse(
        `1a_pre` == 2,
        "contemplative",
        ifelse(
          `1a_pre` == 3,
          "preparation",
          ifelse(
            `1a_pre` == 4,
            "action",
            ifelse(
              `1a_pre` == 5,
              "maintain",
              `1a_pre`
            )
          )
        )
      )
    ),
    rtc_exercise = ifelse(
      `2a_pre` == 1,
      "precontemplative",
      ifelse(
        `2a_pre` == 2,
        "contemplative",
        ifelse(
          `2a_pre` == 3,
          "preparation",
          ifelse(
            `2a_pre` == 4,
            "action",
            ifelse(
              `2a_pre` == 5,
              "maintain",
              `2a_pre`
            )
          )
        )
      )
    ),
    rtc_diet_groups = ifelse(
      `1a_pre` == 1,
      "Pre/Contemplative",
      ifelse(
        `1a_pre` == 2,
        "Pre/Contemplative",
        ifelse(
          `1a_pre` == 3,
          "Preparation",
          ifelse(
            `1a_pre` == 4,
            "Action",
            ifelse(
              `1a_pre` == 5,
              "Maintain",
              `1a_pre`
            )
          )
        )
      )
    ),
    rtc_exercise_groups = ifelse(
    `2a_pre` == 1,
    "Pre/Contemplative",
    ifelse(
      `2a_pre` == 2,
      "Pre/Contemplative",
      ifelse(
        `2a_pre` == 3,
        "Preparation",
        ifelse(
          `2a_pre` == 4,
          "Action",
          ifelse(
            `2a_pre` == 5,
            "Maintain",
            `2a_pre`
          )
        )
      )
    )
  ),
  Include = ifelse(
    is.na(`1a_pre`) |
      is.na(`2a_pre`),
    "FALSE",
    "TRUE"
  ),
  MaxWeightLost = MaxWeightLost*-1
) %>% 
  select(
    rtc_diet,
    rtc_diet_groups,
    rtc_exercise,
    rtc_exercise_groups,
    Include,
    Gender,
    Age,
    `Start weight` = Todays_Weight,
    BMI,
    `Maximum weight lost` = MaxWeightLost,
    `Percent weight lost` = pWeightLost,
    `Lost 7 percent during core` = Met7GoalCore,
    `Lost 7 percent overall` = Met7GoalOVL,
    `Lost 5 percent during core` = Met5GoalCore,
    `Lost 5 percent overall` = Met5GoalOVL,
    `Core attendance` = Core,
    `Post-core attendance` = AfterCore,
    `Overall attendance` = `Number of Sessions`,
    `Met fat goal` = FatGramGoalMet,
    `Met fat goal (percentage of sessions)` = Met_Fat_Gram,
    `Met exercise goal at least 50 percent` = Exercise_Goal_50_Met,
    `Met exercise goal (percentage of sessions)` = Met_Activity_Goal
  ) %>% 
  mutate(
    rtc_diet_groups = as.factor(
      rtc_diet_groups
      ),
    rtc_exercise_groups = as.factor(
      rtc_exercise_groups
      ),
    `Lost 7 percent during core` = ifelse(
      `Lost 7 percent during core` == 1,
      TRUE,
      FALSE
      ),
    `Lost 7 percent overall` = ifelse(
      `Lost 7 percent overall` == 1,
      TRUE,
      FALSE
      ),
    `Lost 5 percent during core` = ifelse(
      `Lost 5 percent during core` == 1,
      TRUE,
      FALSE
    ),
    `Lost 5 percent overall` = ifelse(
      `Lost 5 percent overall` == 1,
      TRUE,
      FALSE
    ),
    `Met fat goal` = ifelse(
      `Met fat goal` == 1,
      TRUE,
      FALSE
    ),
    `Met exercise goal at least 50 percent` = ifelse(
      `Met exercise goal at least 50 percent` == 1,
      TRUE,
      FALSE
    )
  )

df.processed$rtc_diet_groups <- factor(
  df.processed$rtc_diet_groups,
  levels = c("Pre/Contemplative", "Preparation", "Action", "Maintain")
  )

df.processed$rtc_exercise_groups <- factor(
  df.processed$rtc_exercise_groups,
  levels = c("Pre/Contemplative", "Preparation", "Action", "Maintain")
  )

```


# Descriptives

## Comparison between included/excluded individuals

```{r}
tab1 <- compareGroups::compareGroups(
  Include ~ .- rtc_diet_groups - rtc_exercise - rtc_exercise_groups - rtc_diet,
  df.processed
  )

compareGroups::createTable(
  tab1,
  show.p.overall = FALSE
  ) %>% 
  compareGroups::export2md()

```

## Summary statistics of included participants

```{r}
df.processed <- df.processed %>% 
  filter(
    Include == "TRUE"
  )

tab1 <- compareGroups::compareGroups(
   ~ . - Include - rtc_diet_groups - rtc_exercise - rtc_exercise_groups - rtc_diet,
  df.processed
  )

compareGroups::createTable(
  tab1
  ) %>% 
  compareGroups::export2md()
```


# Comparison between groups

## Readiness to change diet

```{r}

chisq <- gmodels::CrossTable(
  df.processed$rtc_diet_groups,
  df.processed$`Lost 7 percent overall`,
  chisq = TRUE
  )

table(df.processed$`Lost 7 percent overall`,
  df.processed$rtc_diet_groups)

```

## Readiness to change exercise

## Age

## Starting weight

## BMI


# Models

What can we predict?

```{r}

binary_vars <- c(
  "Maximum weight lost",
  "Percent weight lost",
  "Lost 7 percent during core",
  "Lost 7 percent overall",
  "Lost 5 percent during core",
  "Lost 5 percent overall",
  "Met fat goal",
  "Met exercise goal at least 50 percent"
  )

cont_vars <- c(
  "Core attendance",
  "Post-core attendance",
  "Overall attendance",
  "Met fat goal (percentage of sessions)",
  "Met exercise goal (percentage of sessions)"
)

model_log <- function(x){
  model <- glm(
    formula = 
      df.processed[[x]] ~ 
      rtc_diet_groups + 
      rtc_exercise_groups + 
      Age +
      Gender +
      BMI, 
    data = df.processed, 
    family = binomial
    ) %>% 
    summary()
  
  return(model$coefficients)
}

model_lm <- function(x){
  model <- glm(
    formula = 
      df.processed[[x]] ~ 
      rtc_diet_groups + 
      rtc_exercise_groups + 
      Age +
      Gender +
      BMI, 
    data = df.processed, 
    family = binomial
    ) %>% 
    summary()
  
  return(model$coefficients)
}

```



